#!/usr/bin/env perl
use strict;
use warnings;

my $number  = shift || die "Usage: perl $0 number m|h|d|w|M|Q|Y m|h|d|w|M|Q|Y use_wks use_qtr\n";
my $from    = shift || 's';
my $to      = shift || 'Y';
my $use_wks = shift // 0;
my $use_qtr = shift // 0;

my $minute_num  = 60; # seconds
my $hour_num    = 60; # minutes
my $day_num     = 24; # hours
my $week_num    = 7;  # days
my $month_num   = $use_wks ? 4 : 30;  # weeks or days
my $quarter_num = 3;  # months
my $year_num    = $use_qtr ? 4 : 12;  # quarters or months

my $seconds  = 0;
my $minutes  = 0;
my $hours    = 0;
my $days     = 0;
my $weeks    = 0;
my $months   = 0;
my $quarters = 0;
my $years    = 0;

if ( $from eq 's' ) {
    $seconds = $number;
}
elsif ( $from eq 'm' ) {
    $minutes = $number;
}
elsif ( $from eq 'h' ) {
    $hours = $number;
}
elsif ( $from eq 'd' ) {
    $days = $number;
}
elsif ( $from eq 'w' ) {
    $weeks = $number;
}
elsif ( $from eq 'M' ) {
    $months = $number;
}
elsif ( $from eq 'Q' ) {
    $quarters = $number;
}
elsif ( $from eq 'Y' ) {
    $years = $number;
}

if ( $from eq 's' ) {
    print "$seconds s\n";
    if ( $seconds >= $minute_num ) {
        ( $minutes, $seconds ) = int_rem( $seconds, $minute_num );
    }
    printf "%dm %ds\n", $minutes, $seconds;
    exit if $to eq 'm';
}

if ( grep { $from eq $_ } qw( s m ) ) {
    if ( $minutes >= $hour_num ) {
        ( $hours, $minutes ) = int_rem( $minutes, $hour_num );
    }
    printf "%dh %dm %ds\n", $hours, $minutes, $seconds;
    exit if $to eq 'h';
}

if ( grep { $from eq $_ } qw( s m h ) ) {
    if ( $hours >= $day_num ) {
        ( $days, $hours ) = int_rem( $hours, $day_num );
    }
    printf "%dd %dh %dm %ds\n", $days, $hours, $minutes, $seconds;
    exit if $to eq 'd';
}

if ( $use_wks ) {
    if ( grep { $from eq $_ } qw( s m h d ) ) {
        if ( $days >= $week_num ) {
            ( $weeks, $days ) = int_rem( $days, $week_num );
        }
        printf "%dw %dd %dh %dm %ds\n",
            $weeks, $days, $hours, $minutes, $seconds;
        exit if $to eq 'w';
    }

    if ( grep { $from eq $_ } qw( s m h d w ) ) {
        if ( $weeks >= $month_num ) {
            ( $months, $weeks ) = int_rem( $weeks, $month_num );
        }
        printf "%dM %dw %dd %dh %dm %ds\n",
            $months, $weeks, $days, $hours, $minutes, $seconds;
        exit if $to eq 'M';
    }
}
else {
    if ( grep { $from eq $_ } qw( s m h d ) ) {
        if ( $days >= $month_num ) {
            ( $months, $days ) = int_rem( $days, $month_num );
        }
        printf "%dM %dd %dh %dm %ds\n",
            $months, $days, $hours, $minutes, $seconds;
        exit if $to eq 'M';
    }
}

if ( $use_qtr ) {
    if ( grep { $from eq $_ } qw( s m h d w M ) ) {
        if ( $months >= $quarter_num ) {
            ( $quarters, $months ) = int_rem( $months, $quarter_num );
        }
        printf "%dQ %dM %dw %dd %dh %dm %ds\n",
            $quarters, $months, $weeks, $days, $hours, $minutes, $seconds;
        exit if $to eq 'Q';
    }

    if ( grep { $from eq $_ } qw( s m h d w M Q ) ) {
        if ( $quarters >= $year_num ) {
            ( $years, $quarters ) = int_rem( $quarters, $year_num );
        }
        printf "%dY %dQ %dM %dw %dd %dh %dm %ds\n",
            $years, $quarters, $months, $weeks, $days, $hours, $minutes, $seconds;
    }
}
else {
    if ( grep { $from eq $_ } qw( s m h d w M ) ) {
        if ( $months >= $year_num ) {
            ( $years, $months ) = int_rem( $months, $year_num );
        }
        printf "%dY %dM %dw %dd %dh %dm %ds\n",
            $years, $months, $weeks, $days, $hours, $minutes, $seconds;
    }
}

sub int_rem {
    my ( $frame, $factor ) = @_;

    my $integer   = int $frame / $factor;
    my $remainder = $frame % $factor;

    return $integer, $remainder;
}
