#!/usr/bin/env perl
use strict;
use warnings;

my $number  = shift || die "Usage: perl $0 number m|h|d|w|M|Q|Y m|h|d|w|M|Q|Y use_wks use_qtr\n";
my $from    = shift || 's';
my $to      = shift || 'Y';
my $use_wks = shift // 0;
my $use_qtr = shift // 0;

my %span = (
    minute  => 60, # seconds
    hour    => 60, # minutes
    day     => 24, # hours
    week    => 7,  # days
    month   => $use_wks ? 4 : 30,  # weeks or days
    quarter => 3,  # months
    year    => $use_qtr ? 4 : 12,  # quarters or months
);

my $seconds  = 0;
my $minutes  = 0;
my $hours    = 0;
my $days     = 0;
my $weeks    = 0;
my $months   = 0;
my $quarters = 0;
my $years    = 0;

if ( $from eq 's' ) {
    $seconds = $number;
}
elsif ( $from eq 'm' ) {
    $minutes = $number;
}
elsif ( $from eq 'h' ) {
    $hours = $number;
}
elsif ( $from eq 'd' ) {
    $days = $number;
}
elsif ( $from eq 'w' ) {
    $weeks = $number;
}
elsif ( $from eq 'M' ) {
    $months = $number;
}
elsif ( $from eq 'Q' ) {
    $quarters = $number;
}
elsif ( $from eq 'Y' ) {
    $years = $number;
}

if ( $from eq 's' ) {
    print "$seconds s\n";
    if ( $seconds >= $span{minute} ) {
        ( $minutes, $seconds ) = int_rem( $seconds, $span{minute} );
    }
    printf "%dm %ds\n", $minutes, $seconds;
    exit if $to eq 'm';
}

if ( grep { $from eq $_ } qw( s m ) ) {
    if ( $minutes >= $span{hour} ) {
        ( $hours, $minutes ) = int_rem( $minutes, $span{hour} );
    }
    printf "%dh %dm %ds\n", $hours, $minutes, $seconds;
    exit if $to eq 'h';
}

if ( grep { $from eq $_ } qw( s m h ) ) {
    if ( $hours >= $span{day} ) {
        ( $days, $hours ) = int_rem( $hours, $span{day} );
    }
    printf "%dd %dh %dm %ds\n", $days, $hours, $minutes, $seconds;
    exit if $to eq 'd';
}

if ( $use_wks ) {
    if ( grep { $from eq $_ } qw( s m h d ) ) {
        if ( $days >= $span{week} ) {
            ( $weeks, $days ) = int_rem( $days, $span{week} );
        }
        printf "%dw %dd %dh %dm %ds\n",
            $weeks, $days, $hours, $minutes, $seconds;
        exit if $to eq 'w';
    }

    if ( grep { $from eq $_ } qw( s m h d w ) ) {
        if ( $weeks >= $span{month} ) {
            ( $months, $weeks ) = int_rem( $weeks, $span{month} );
        }
        printf "%dM %dw %dd %dh %dm %ds\n",
            $months, $weeks, $days, $hours, $minutes, $seconds;
        exit if $to eq 'M';
    }
}
else {
    if ( grep { $from eq $_ } qw( s m h d ) ) {
        if ( $days >= $span{month} ) {
            ( $months, $days ) = int_rem( $days, $span{month} );
        }
        printf "%dM %dd %dh %dm %ds\n",
            $months, $days, $hours, $minutes, $seconds;
        exit if $to eq 'M';
    }
}

if ( $use_qtr ) {
    if ( grep { $from eq $_ } qw( s m h d w M ) ) {
        if ( $months >= $span{quarter} ) {
            ( $quarters, $months ) = int_rem( $months, $span{quarter} );
        }
        printf "%dQ %dM %dw %dd %dh %dm %ds\n",
            $quarters, $months, $weeks, $days, $hours, $minutes, $seconds;
        exit if $to eq 'Q';
    }

    if ( grep { $from eq $_ } qw( s m h d w M Q ) ) {
        if ( $quarters >= $span{year} ) {
            ( $years, $quarters ) = int_rem( $quarters, $span{year} );
        }
        printf "%dY %dQ %dM %dw %dd %dh %dm %ds\n",
            $years, $quarters, $months, $weeks, $days, $hours, $minutes, $seconds;
    }
}
else {
    if ( grep { $from eq $_ } qw( s m h d w M ) ) {
        if ( $months >= $span{year} ) {
            ( $years, $months ) = int_rem( $months, $span{year} );
        }
        printf "%dY %dM %dw %dd %dh %dm %ds\n",
            $years, $months, $weeks, $days, $hours, $minutes, $seconds;
    }
}

sub int_rem {
    my ( $frame, $span ) = @_;

    my $integer   = int $frame / $span;
    my $remainder = $frame % $span;

    return $integer, $remainder;
}
