#!/usr/bin/env perl
use strict;
use warnings;

use Getopt::Long;
use MealMaster;

my $file;
my $title;
my $category;
my $ingredient;
GetOptions(
    'file=s'       => \$file,
    'title=s'      => \$title,
    'category=s'   => \$category,
    'ingredient=s' => \$ingredient,
) or die "Error in command line arguments\n";;

my $mm = MealMaster->new();

my @recipes = $mm->parse($file);

@recipes = grep { $_->title =~ /$title/i } @recipes
    if $title;

my $i = 0;

for my $recipe ( @recipes ) {
    printf "%d. %s\n", ++$i, ucfirst( lc( $recipe->title ) );
    printf "\tCategories: %s\n", join( ', ', sort @{ $recipe->categories } );
    printf "\tYield: %s\n\n", $recipe->yield;
}
