#!/usr/bin/env perl
use strict;
use warnings;

use Getopt::Long;
use MealMaster;

my $file;
my $title;
my $category;
my $ingredients;
GetOptions(
    'file=s'        => \$file,
    'title=s'       => \$title,
    'category=s'    => \$category,
    'ingredients=s' => \$ingredients,
) or die "Error in command line arguments\n";;

my $mm = MealMaster->new();

my @recipes = $mm->parse($file);

@recipes = grep { $_->title =~ /$title/i } @recipes
    if $title;

my $i = 0;

for my $recipe ( @recipes ) {
    if ($category) {
        next unless grep { $_ =~ /$category/i } @{ $recipe->categories };
    }
    if ($ingredients) {
        next unless grep { $_->product =~ /$ingredients/i } @{ $recipe->ingredients };
    }

    printf "%d. %s\n", ++$i, ucfirst( lc( $recipe->title ) );
    printf "\tCategories: %s\n", join( ', ', sort @{ $recipe->categories } );
    printf "\tYield: %s\n", $recipe->yield;
    print "\tIngredients:\n";
    for my $i ( @{ $recipe->ingredients} ) {
        print "\t\t", $i->quantity,
               " ", $i->measure,
               " ", $i->product, 
               "\n";
  }
}
