#!/usr/bin/env perl
use strict;
use warnings;

use IO::Prompt::Tiny qw/prompt/;
use Devel::Examine::Subs;

my @files = @ARGV;
die "Usage: perl $0 /some/perl/File.pm [/another/file.pl ...]\n" unless @files;

my $i = 0;

for my $file ( @files ) {
    $i++;

    print "\n$i. Processing $file...\n";

    my $des = Devel::Examine::Subs->new( file => $file );

    my $subs = $des->all;

    my $j = 0;

    ROUTINE:
    for my $sub ( @$subs ) {
        $j++;
        print "\t$j. $sub\n";

        my $response = prompt( "\tEnter=next q=quit g=grep", '' );

        if ( $response eq 'q' ) {
          last ROUTINE;
        }
        elsif ( $response eq 'g' ) {
            my $res = qx{ grep -rc $sub * | grep -v :0 };
            print $res, "\n";
        }
        else {
          next ROUTINE;
        }
    }
}
